"""Puertos (interfaces) de persistencia.

La capa de aplicación depende únicamente de estos `Protocol`, nunca de
SQLAlchemy. La capa de infraestructura los implementa contra Postgres.
Esto es lo que permite testear los casos de uso con repositorios falsos
y cambiar de motor de base de datos sin tocar la lógica de negocio.
"""
from __future__ import annotations

from typing import Protocol

from app.domain.entities import (
    Categoria,
    Cliente,
    MovimientoInventario,
    OrdenCompra,
    OrdenEnvio,
    PedidoCliente,
    Producto,
    Proveedor,
    ProveedorProducto,
    SolicitudPresupuesto,
    Usuario,
)


class UsuarioRepository(Protocol):
    def get_by_id(self, usuario_id: int) -> Usuario | None: ...
    def get_by_email(self, email: str) -> Usuario | None: ...
    def add(self, usuario: Usuario) -> Usuario: ...
    def update(self, usuario: Usuario) -> Usuario: ...
    def list_by_rol(self, rol: str) -> list[Usuario]: ...


class CategoriaRepository(Protocol):
    def list(self, solo_activas: bool = False) -> list[Categoria]: ...
    def get_by_id(self, categoria_id: int) -> Categoria | None: ...
    def add(self, categoria: Categoria) -> Categoria: ...
    def update(self, categoria: Categoria) -> Categoria: ...
    def delete(self, categoria_id: int) -> None: ...


class ProductoRepository(Protocol):
    def list(
        self, solo_activos: bool = False, categoria_id: int | None = None, busqueda: str | None = None
    ) -> list[Producto]: ...
    def get_by_id(self, producto_id: int) -> Producto | None: ...
    def add(self, producto: Producto) -> Producto: ...
    def update(self, producto: Producto) -> Producto: ...
    def delete(self, producto_id: int) -> None: ...
    def siguiente_codigo(self) -> str: ...


class ClienteRepository(Protocol):
    def list(
        self, busqueda: str | None = None, activo: bool | None = None, ciudad: str | None = None
    ) -> list[Cliente]: ...
    def get_by_id(self, cliente_id: int) -> Cliente | None: ...
    def add(self, cliente: Cliente) -> Cliente: ...
    def update(self, cliente: Cliente) -> Cliente: ...
    def delete(self, cliente_id: int) -> None: ...
    def tiene_pedidos(self, cliente_id: int) -> bool: ...
    def ciudades(self) -> list[str]: ...


class ProveedorRepository(Protocol):
    def list(self, solo_activos: bool = False) -> list[Proveedor]: ...
    def get_by_id(self, proveedor_id: int) -> Proveedor | None: ...
    def get_by_user_id(self, user_id: int) -> Proveedor | None: ...
    def add(self, proveedor: Proveedor) -> Proveedor: ...
    def update(self, proveedor: Proveedor) -> Proveedor: ...
    def delete(self, proveedor_id: int) -> None: ...


class ProveedorProductoRepository(Protocol):
    def list(
        self, proveedor_id: int | None = None, producto_id: int | None = None, disponible: bool | None = None
    ) -> list[ProveedorProducto]: ...
    def get_by_id(self, item_id: int) -> ProveedorProducto | None: ...
    def existe(self, proveedor_id: int, producto_id: int) -> bool: ...
    def add(self, item: ProveedorProducto) -> ProveedorProducto: ...
    def update(self, item: ProveedorProducto) -> ProveedorProducto: ...
    def delete(self, item_id: int) -> None: ...


class PedidoClienteRepository(Protocol):
    def list(self, estado: str | None = None, busqueda: str | None = None) -> list[PedidoCliente]: ...
    def get_by_id(self, pedido_id: int) -> PedidoCliente | None: ...
    def add(self, pedido: PedidoCliente) -> PedidoCliente: ...
    def update(self, pedido: PedidoCliente) -> PedidoCliente: ...
    def replace_items(self, pedido_id: int, items: list) -> None: ...
    def delete(self, pedido_id: int) -> None: ...
    def siguiente_numero(self) -> str: ...
    def contar_activos(self) -> int: ...
    def contar_creados_hoy(self) -> int: ...


class SolicitudPresupuestoRepository(Protocol):
    def list(
        self, estado: str | None = None, proveedor_id: int | None = None, pedido_cliente_id: int | None = None
    ) -> list[SolicitudPresupuesto]: ...
    def get_by_id(self, solicitud_id: int) -> SolicitudPresupuesto | None: ...
    def add(self, solicitud: SolicitudPresupuesto) -> SolicitudPresupuesto: ...
    def update(self, solicitud: SolicitudPresupuesto) -> SolicitudPresupuesto: ...
    def delete(self, solicitud_id: int) -> None: ...
    def siguiente_numero(self) -> str: ...
    def existe_activa(self, pedido_cliente_id: int, proveedor_id: int) -> bool: ...
    def contar_pendientes(self) -> int: ...
    def contar_cotizadas(self) -> int: ...


class OrdenCompraRepository(Protocol):
    def list(self, estado: str | None = None, busqueda: str | None = None) -> list[OrdenCompra]: ...
    def get_by_id(self, orden_id: int) -> OrdenCompra | None: ...
    def add(self, orden: OrdenCompra) -> OrdenCompra: ...
    def update(self, orden: OrdenCompra) -> OrdenCompra: ...
    def replace_items(self, orden_id: int, items: list) -> None: ...
    def delete(self, orden_id: int) -> None: ...
    def siguiente_numero(self) -> str: ...
    def contar_activas(self) -> int: ...


class OrdenEnvioRepository(Protocol):
    def list(self, estado: str | None = None, busqueda: str | None = None) -> list[OrdenEnvio]: ...
    def get_by_id(self, orden_id: int) -> OrdenEnvio | None: ...
    def add(self, orden: OrdenEnvio) -> OrdenEnvio: ...
    def update(self, orden: OrdenEnvio) -> OrdenEnvio: ...
    def delete(self, orden_id: int) -> None: ...
    def siguiente_numero(self) -> str: ...
    def contar_pendientes(self) -> int: ...


class MovimientoInventarioRepository(Protocol):
    def add(self, movimiento: MovimientoInventario) -> MovimientoInventario: ...
    def list(
        self, producto_id: int | None = None, tipo: str | None = None, limit: int | None = None
    ) -> list[MovimientoInventario]: ...
