"""caja y venta de mostrador

Revision ID: 5b4211eced37
Revises: 4e3f668fd87f
Create Date: 2026-09-18 02:49:26.030166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b4211eced37'
down_revision: Union[str, Sequence[str], None] = '4e3f668fd87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caja_turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fondo_inicial', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('total_ventas_efectivo', sa.Integer(), nullable=False),
    sa.Column('total_ventas_tarjeta', sa.Integer(), nullable=False),
    sa.Column('total_ventas_transferencia', sa.Integer(), nullable=False),
    sa.Column('conteo_fisico', sa.Integer(), nullable=True),
    sa.Column('diferencia', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caja_turnos_estado'), 'caja_turnos', ['estado'], unique=False)
    op.create_table('movimientos_caja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caja_turno_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_turno_id'], ['caja_turnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas_mostrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('caja_turno_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caja_turno_id'], ['caja_turnos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_ventas_mostrador_caja_turno_id'), 'ventas_mostrador', ['caja_turno_id'], unique=False)
    op.create_index(op.f('ix_ventas_mostrador_created_at'), 'ventas_mostrador', ['created_at'], unique=False)
    op.create_table('venta_mostrador_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_mostrador.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_mostrador_items')
    op.drop_index(op.f('ix_ventas_mostrador_created_at'), table_name='ventas_mostrador')
    op.drop_index(op.f('ix_ventas_mostrador_caja_turno_id'), table_name='ventas_mostrador')
    op.drop_table('ventas_mostrador')
    op.drop_table('movimientos_caja')
    op.drop_index(op.f('ix_caja_turnos_estado'), table_name='caja_turnos')
    op.drop_table('caja_turnos')
    # ### end Alembic commands ###
